apiVersion: v1
kind: Service
metadata:
  {{- if .Values.deployment.namespace.create }} 
  namespace: {{ .Values.deployment.namespace.name }}
  {{- end }}
  creationTimestamp: null
  labels:
    app: prometheus
  name: prometheus-svc
spec:
  ports:
  - name: prometheus-svc
    port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  type: NodePort
status:
  loadBalancer: {}
